In [1]:
import torch
import torchvision
import numpy as np

In [2]:
dataset = torchvision.datasets.CIFAR10(root='./data', train=True, download=True)
image = dataset.data[0]

Files already downloaded and verified


# PyTorch i obrazy

In [3]:
image_tensor = torch.from_numpy(image)

In [4]:
type(image_tensor)

torch.Tensor

In [5]:
image_tensor.shape

torch.Size([32, 32, 3])

In [6]:
image_tensor

tensor([[[ 59,  62,  63],
         [ 43,  46,  45],
         [ 50,  48,  43],
         ...,
         [158, 132, 108],
         [152, 125, 102],
         [148, 124, 103]],

        [[ 16,  20,  20],
         [  0,   0,   0],
         [ 18,   8,   0],
         ...,
         [123,  88,  55],
         [119,  83,  50],
         [122,  87,  57]],

        [[ 25,  24,  21],
         [ 16,   7,   0],
         [ 49,  27,   8],
         ...,
         [118,  84,  50],
         [120,  84,  50],
         [109,  73,  42]],

        ...,

        [[208, 170,  96],
         [201, 153,  34],
         [198, 161,  26],
         ...,
         [160, 133,  70],
         [ 56,  31,   7],
         [ 53,  34,  20]],

        [[180, 139,  96],
         [173, 123,  42],
         [186, 144,  30],
         ...,
         [184, 148,  94],
         [ 97,  62,  34],
         [ 83,  53,  34]],

        [[177, 144, 116],
         [168, 129,  94],
         [179, 142,  87],
         ...,
         [216, 184, 140],
        

In [7]:
image_tensor[4:-4, 4:-4]

tensor([[[124,  77,  36],
         [121,  77,  36],
         [120,  78,  40],
         ...,
         [127,  84,  45],
         [121,  79,  41],
         [119,  79,  40]],

        [[136,  88,  45],
         [131,  84,  42],
         [129,  84,  43],
         ...,
         [136,  97,  64],
         [120,  80,  45],
         [107,  68,  34]],

        [[136,  88,  44],
         [132,  83,  40],
         [122,  74,  30],
         ...,
         [151, 106,  69],
         [129,  87,  49],
         [108,  68,  36]],

        ...,

        [[135,  90,  45],
         [139,  94,  49],
         [153, 108,  68],
         ...,
         [136, 112,  52],
         [127, 105,  39],
         [121,  92,  39]],

        [[122,  76,  41],
         [134,  88,  49],
         [142,  98,  53],
         ...,
         [143, 105,  54],
         [130,  93,  44],
         [132,  90,  46]],

        [[131,  88,  34],
         [126,  82,  35],
         [138,  94,  49],
         ...,
         [149, 109,  63],
        

In [8]:
image_tensor[4:-4, 4:-4].shape

torch.Size([24, 24, 3])

In [9]:
image_tensor[0, 0, 0]

tensor(59, dtype=torch.uint8)

In [10]:
int(image_tensor[0, 0, 0])

59

In [11]:
image_tensor.numpy()

array([[[ 59,  62,  63],
        [ 43,  46,  45],
        [ 50,  48,  43],
        ...,
        [158, 132, 108],
        [152, 125, 102],
        [148, 124, 103]],

       [[ 16,  20,  20],
        [  0,   0,   0],
        [ 18,   8,   0],
        ...,
        [123,  88,  55],
        [119,  83,  50],
        [122,  87,  57]],

       [[ 25,  24,  21],
        [ 16,   7,   0],
        [ 49,  27,   8],
        ...,
        [118,  84,  50],
        [120,  84,  50],
        [109,  73,  42]],

       ...,

       [[208, 170,  96],
        [201, 153,  34],
        [198, 161,  26],
        ...,
        [160, 133,  70],
        [ 56,  31,   7],
        [ 53,  34,  20]],

       [[180, 139,  96],
        [173, 123,  42],
        [186, 144,  30],
        ...,
        [184, 148,  94],
        [ 97,  62,  34],
        [ 83,  53,  34]],

       [[177, 144, 116],
        [168, 129,  94],
        [179, 142,  87],
        ...,
        [216, 184, 140],
        [151, 118,  84],
        [123,  92,  72]]

In [12]:
image.shape

(32, 32, 3)

In [13]:
image.transpose(2, 0, 1).shape

(3, 32, 32)

In [14]:
image_tensor.permute(2, 0, 1).shape

torch.Size([3, 32, 32])

In [15]:
image_tensor.reshape(-1).shape

torch.Size([3072])

In [16]:
image_tensor.reshape(2, -1).shape

torch.Size([2, 1536])

In [17]:
image_tensor.dtype

torch.uint8

In [18]:
image_tensor_float = image_tensor.type(torch.float16)

In [19]:
image_tensor_float.dtype

torch.float16

In [20]:
image_tensor_float.shape

torch.Size([32, 32, 3])

In [21]:
image_tensor_float.mean(2) 

tensor([[ 61.3438,  44.6562,  47.0000,  ..., 132.6250, 126.3125, 125.0000],
        [ 18.6719,   0.0000,   8.6641,  ...,  88.6875,  84.0000,  88.6875],
        [ 23.3281,   7.6680,  28.0000,  ...,  84.0000,  84.6875,  74.6875],
        ...,
        [158.0000, 129.3750, 128.3750,  ..., 121.0000,  31.3281,  35.6562],
        [138.3750, 112.6875, 120.0000,  ..., 142.0000,  64.3125,  56.6562],
        [145.6250, 130.3750, 136.0000,  ..., 180.0000, 117.6875,  95.6875]],
       dtype=torch.float16)

In [22]:
image_tensor_float.mean(2).shape

torch.Size([32, 32])

In [23]:
image_tensor_float.shape

torch.Size([32, 32, 3])

In [24]:
image_tensor_float.sum(0)

tensor([[4336., 3356., 2234.],
        [4086., 2816., 1309.],
        [4232., 3006., 1476.],
        [4372., 3048., 1487.],
        [4344., 3034., 1552.],
        [4164., 2944., 1517.],
        [4236., 3064., 1722.],
        [4512., 3340., 2084.],
        [4768., 3624., 2460.],
        [4952., 3808., 2688.],
        [4700., 3436., 2228.],
        [4632., 3260., 1949.],
        [4840., 3528., 2224.],
        [4920., 3764., 2580.],
        [4668., 3540., 2440.],
        [4760., 3546., 2448.],
        [5040., 3714., 2526.],
        [5048., 3696., 2436.],
        [4876., 3608., 2396.],
        [4668., 3452., 2252.],
        [4732., 3552., 2284.],
        [4716., 3620., 2312.],
        [4748., 3692., 2528.],
        [4716., 3608., 2668.],
        [4768., 3664., 2482.],
        [4468., 3362., 1888.],
        [4032., 3036., 1490.],
        [3860., 2922., 1384.],
        [4208., 3246., 1594.],
        [4384., 3432., 1751.],
        [3998., 2998., 1522.],
        [3804., 2904., 1658.]], dtype=t

In [25]:
image_tensor_float.sum(0).shape

torch.Size([32, 3])

In [26]:
t1 = torch.randn(2, 4)
t2 = torch.randn(4, 2)

In [27]:
t1.shape, t2.shape

(torch.Size([2, 4]), torch.Size([4, 2]))

In [28]:
t1

tensor([[-0.2547, -1.0205,  1.2140,  0.1289],
        [-0.2486, -1.2183, -1.1439, -0.5640]])

In [29]:
t2

tensor([[ 0.5976,  1.0356],
        [ 0.2422,  0.8277],
        [-1.2574, -1.0539],
        [ 1.1323, -1.0765]])

In [30]:
t1 * t2

RuntimeError: The size of tensor a (4) must match the size of tensor b (2) at non-singleton dimension 1

In [31]:
t2.T

tensor([[ 0.5976,  0.2422, -1.2574,  1.1323],
        [ 1.0356,  0.8277, -1.0539, -1.0765]])

In [32]:
t1 * t2.T

tensor([[-0.1522, -0.2472, -1.5265,  0.1460],
        [-0.2574, -1.0084,  1.2056,  0.6071]])

In [33]:
t1 @ t2

tensor([[-1.7799, -2.5266],
        [ 0.3562,  0.5468]])

In [34]:
t2 @ t1

tensor([[-0.4096, -1.8714, -0.4591, -0.5070],
        [-0.2674, -1.2556, -0.6528, -0.4356],
        [ 0.5822,  2.5671, -0.3210,  0.4322],
        [-0.0208,  0.1559,  2.6060,  0.7531]])

In [35]:
t1

tensor([[-0.2547, -1.0205,  1.2140,  0.1289],
        [-0.2486, -1.2183, -1.1439, -0.5640]])

In [36]:
if torch.cuda.is_available():
    t1 = t1.to('cuda')

In [37]:
t1.device

device(type='cpu')