# Podobieństwo tekstu

- słów
- dokumentów

## Podobieństwo słów

```
pip install jellyfish
```

In [1]:
import pandas as pd
import numpy as np
import fasttext
import jellyfish
import spacy

nlp = spacy.load("pl_core_news_md")
ft = fasttext.load_model("cc.pl.300.bin")

```
ziemniak
ziemnjak
iemniak
kartofel
```

### Hamming

In [2]:
jellyfish.hamming_distance("ziemniak", "ziemnjak")

1

In [3]:
jellyfish.hamming_distance("ziemniak", "iemniak")

8

In [4]:
jellyfish.hamming_distance("ziemniak", "kartofel")

8

### Levenshtein



In [5]:
jellyfish.levenshtein_distance("ziemniak", "ziemnjak")

1

In [6]:
jellyfish.levenshtein_distance("ziemniak", "iemniak")

1

In [7]:
jellyfish.levenshtein_distance("ziemniak", "kartofel")

8

### Cosinus

In [8]:
from sklearn.metrics.pairwise import cosine_similarity

In [9]:
w1 = ft.get_word_vector("ziemniak")
w2 = ft.get_word_vector("ziemnjak")
w3 = ft.get_word_vector("iemniak")
w4 = ft.get_word_vector("kartofel")

In [10]:
cosine_similarity((w1, w2))

array([[1.        , 0.31650072],
       [0.31650072, 0.9999998 ]], dtype=float32)

In [11]:
ft.get_subwords("ziemniak")

(['ziemniak', '<ziem', 'ziemn', 'iemni', 'emnia', 'mniak', 'niak>'],
 array([  93004, 3555220, 2003060, 3545679, 2207861, 2800225, 2474106]))

In [12]:
ft.get_subwords("ziemnjak")

(['<ziem', 'ziemn', 'iemnj', 'emnja', 'mnjak', 'njak>'],
 array([3555220, 2003060, 2323298, 2956006, 2145392, 3266749]))

In [13]:
cosine_similarity((w1, w3))

array([[1.        , 0.45804375],
       [0.45804375, 0.9999999 ]], dtype=float32)

In [14]:
cosine_similarity((w1, w4))

array([[1.        , 0.6329498 ],
       [0.6329498 , 0.99999964]], dtype=float32)

In [15]:
t1 = nlp("ziemniak")[0]
t4 = nlp("kartofel")[0]

In [16]:
cosine_similarity((t1.vector, t4.vector))

array([[1.        , 0.35773095],
       [0.35773095, 1.0000001 ]], dtype=float32)

In [17]:
t1.similarity(t4)

0.35773084